.github/workflows/repo_checks.yml
.github/workflows/tests.yml
Pipfile
pytest.ini
tests/test_schemas.py

#6 Add basic workflows

---

json_schemas/api_gadget_data.json

#9 Replaced "name" field with "id"

---

.github/workflows/wiki_export.yml

#15 Added missing python setup

---

.github/workflows/wiki_export.yml

#17 Fix wiki export pipeline not using pipenv

---

.github/workflows/wiki_export.yml

#19 Changed github user settings

---

api_docs/api_specs.json
api_params.h
api_params.py

#22 Removed gadget sync from api

---

exporters/api_doc_exporter.py
exporters/doc_exporter.py
exporters/gadget_doc_exporter.py
exporters/script_params.py
utils/markdown_file.py

Fb 21 add link to constants file to api docs

---

api_definitions.h
api_definitions.py
api_docs/api_specs.json
exporters/gadget_doc_exporter.py
gadget_docs/gadget_specs.json
gadget_docs/gadget_specs_schema.json
json_schemas/client_gadget_config.json

Fb 28 extended gadget config

---

.github/workflows/repo_checks.yml

#33 Made repo checks primary-branch independent

---

api_definitions.h
exporters/api_constants_exporter.py
exporters/constants_exporter.py
exporters/gadget_constants_exporter.py
exporters/script_params.py
gadget_definitions.h
utils/cpp_file.py

Fb 30 code generator classes

---

api_definitions.h
exporters/api_constants_exporter.py
exporters/gadget_constants_exporter.py
gadget_definitions.h

#40 CPP problems

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
json_schemas/api_bridge_update_check_response.json
json_schemas/api_bridge_update_response.json

#44 Added the paths to api_specs, created new response

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
json_schemas/api_client_data.json

Fb 43 api version

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
api_docs/api_specs_schema.json
exporters/api_constants_exporter.py
exporters/script_params.py

Fb 49 add access level api

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
api_docs/api_specs_schema.json
export.py
exporters/api_constants_exporter.py
exporters/api_doc_exporter.py
exporters/doc_exporter.py

Fb 54 split api doc

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
exporters/api_doc_exporter.py
utils/markdown_file.py

Fb 53 access level documentation

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
api_docs/api_specs_schema.json
exporters/api_doc_exporter.py

Fb 55 read write access

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
export.py
exporters/api_constants_exporter.py
exporters/script_params.py
tests/test_doc_exporters.py
utils/api_endpoint_definition.py

Fb 56 rebuild python api constants

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
exporters/api_constants_exporter.py
exporters/script_params.py
utils/api_endpoint_definition.py

Fb 64 uti to api def

---

api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
json_schemas/api_get_all_gadget_publishers.json

#75 Adding api definitions for reading gadget publishers

---

ApiDefinitions.swift
api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
json_schemas/api_bridge_add_user.json

Fb 83 api add user

---

ApiDefinitions.swift
api_definitions.h
api_definitions.js
api_definitions.py
api_docs/api_specs.json
utils/markdown_file.py

#93 Updating markdown file
